server:
  port: 8081 # Port dành riêng cho Identity

spring:
  application:
    name: identity-service
    
  # Cấu hình Database H2 chạy trên RAM
  datasource:
    url: jdbc:h2:mem:identitydb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate # Tắt chế độ tự tạo bảng của Hibernate để nhường cho Flyway
    show-sql: true # In câu lệnh SQL ra console để dễ học
    
  h2:
    console:
      enabled: true # Mở giao diện web để xem database
      path: /h2-console

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET}
