version: '3.8'
services:
  # MariaDB Database (Tương thích MySQL)
  mariadb:
    image: mariadb:11.7.2
    container_name: banking_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banking_identity
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: banking_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mariadb_data:
  redis_data:
