server:
  port: 8083

spring:
  application:
    name: transfer-service
  datasource:
    url: jdbc:h2:file:./transferdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Cấu hình Feign Client (RPC qua HTTP)
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
