server:
  port: 8082

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    driver-class-name: oracle.jdbc.OracleDriver
    username: account_db
    password: password
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: account-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
